name: 'Handle stale discussions'
description: 'Custom GH action on discussions'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: orange
  icon: cloud
inputs:
  attention-label:
    description: 'Label to add to stale discussions'
    required: false
    default: 'attention'
  github-token:
    description: 'GitHub token'
    required: false
  days-until-stale:
    description: 'Number of days of inactivity before a discussion is considered stale'
    required: false
    default: 7
  close-locked-discussions:
    description: 'Close locked discussions'
    required: false
    default: true
  close-answered-discussions:
    description: 'Close answered discussions'
    required: false
    default: true
  stale-response-text:
    description: 'Comment to post when marking a discussion as stale'
    required: false
  instructions-response-text:
    description: 'Comment to post when a proposed answer is given'
    required: false
  proposed-answer-keyword:
    description: 'Keyword to use to indicate a proposed answer'
    required: false
    default: '@github-actions proposed-answer'
  close-stale-as-answered:
    description: 'Close stale discussions as answered'
    required: false
    default: false
